### PR TITLE
add translation for Chinese

### PR DESCRIPTION
**Pull request by flaribbit**

### CODE REVIEW

**Comment by maxwellito** [comment]
Hi there,

Thank you so much for your translation and the PR. It looks good, I just
have an issue on my machine to build the project. Once this is sorted and I
can test your changes, then Ill approve the PR and merge it.

Thanks for your help, it's very sweet to have another translation to the
project!

(Sorry about the delay)

**Comment by flaribbit** [comment]
Never mind, I also got an issue, fixed now. Maybe we can get github actions to build it for us.

**Comment by flaribbit** [comment]
Done, now Github Actions will build it and update gh-pages branch.

**Review by maxwellito — APPROVED** [review]
LGTM!

**Comment by maxwellito** [comment]
Thanks for your amazing work! I might make some changes on the Github Actions (to not run on pull_requests) but this is fantastic!

**Pull request merged**
